\set ON_ERROR_STOP on
-- ============================================================
-- 039_controle_apontamentos_DEV_PROPOSTA_GAIA.sql
-- Projeto FugaPET_Dev  |  Schema: desenvolvimento
-- Modulo: Controle de Apontamentos de Producao (leitura do codigo de barras da operacao da OP)
--
-- EXECUCAO CONTROLADA - NAO EXECUTAR AUTOMATICAMENTE.
-- Aplicar SOMENTE apos o PREFLIGHT passar. Transacional e IDEMPOTENTE. NAO altera/apaga dados.
--
-- Numeracao: 038 JA ESTA EM USO (038_cancelamento_lancamento_semi_acabado_GAIA). Este pacote e o 039.
--
-- Objetos criados/garantidos:
--   operacao_producao_configuracao -> roteamento da operacao SAP para a tela (POR DADOS, nunca por descricao)
--   operacao_producao_apontamento  -> apontamento da operacao (inicio -> termino)
--   operacao_producao_evento       -> auditoria de CADA leitura (codigo original preservado)
--   Permissoes da rotina CONTROLE_APONTAMENTOS (proposta; so insere se a matriz existir)
-- ============================================================
SET search_path TO desenvolvimento;

BEGIN;

-- Timeouts conservadores (padrao dos incrementais aprovados): nao esperar lock indefinidamente e nao
-- deixar DDL rodando sem limite. LOCAL = valem so nesta transacao.
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

-- ============================================================
-- 1. CONFIGURACAO: operacao SAP -> tela de destino
-- ============================================================
CREATE TABLE IF NOT EXISTS desenvolvimento.operacao_producao_configuracao
(
    codigo_configuracao      bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    centro                   varchar(10)  NOT NULL DEFAULT '',
    tipo_ordem               varchar(10)  NOT NULL DEFAULT '',
    sequencia_sap            varchar(10)  NOT NULL DEFAULT '',
    operacao_sap             varchar(10)  NOT NULL,
    suboperacao_sap          varchar(10)  NOT NULL DEFAULT '',
    centro_trabalho          varchar(20)  NOT NULL DEFAULT '',
    tipo_processo            varchar(40)  NOT NULL,
    tela_destino             varchar(80)  NOT NULL DEFAULT '',
    exige_operacao_anterior  boolean      NOT NULL DEFAULT false,
    ativo                    boolean      NOT NULL DEFAULT true,
    criado_em                timestamptz  NOT NULL DEFAULT now(),
    criado_por               varchar(80)  NOT NULL DEFAULT '',
    alterado_em              timestamptz,
    alterado_por             varchar(80)
);

DO $$
BEGIN
    -- Tipos de processo aceitos (espelha TipoProcessoOperacao no codigo).
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_operacao_config_tipo_processo'
                     AND conrelid = 'desenvolvimento.operacao_producao_configuracao'::regclass) THEN
        ALTER TABLE desenvolvimento.operacao_producao_configuracao
            ADD CONSTRAINT ck_operacao_config_tipo_processo
            CHECK (tipo_processo IN (
                'CONSUMO_MATERIA_PRIMA','CONSUMO_QUIMICOS','SEMI_ACABADO','PRODUTO_ACABADO','SEM_DESTINO_CONFIGURADO'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_operacao_config_operacao_nao_vazia'
                     AND conrelid = 'desenvolvimento.operacao_producao_configuracao'::regclass) THEN
        ALTER TABLE desenvolvimento.operacao_producao_configuracao
            ADD CONSTRAINT ck_operacao_config_operacao_nao_vazia
            CHECK (length(trim(operacao_sap)) > 0);
    END IF;
END $$;

-- Uma unica configuracao ATIVA por combinacao. CENTRO_TRABALHO faz parte da chave: a mesma operacao
-- pode ter destinos diferentes em centros de trabalho diferentes.
CREATE UNIQUE INDEX IF NOT EXISTS uq_operacao_config_ativa
    ON desenvolvimento.operacao_producao_configuracao
       (centro, tipo_ordem, sequencia_sap, operacao_sap, suboperacao_sap, centro_trabalho)
    WHERE ativo = true;

CREATE INDEX IF NOT EXISTS ix_operacao_config_operacao
    ON desenvolvimento.operacao_producao_configuracao (operacao_sap) WHERE ativo = true;

-- ============================================================
-- 2. APONTAMENTO da operacao
-- ============================================================
CREATE TABLE IF NOT EXISTS desenvolvimento.operacao_producao_apontamento
(
    codigo_apontamento        bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_ordem              varchar(40)  NOT NULL,
    item_ordem                varchar(20)  NOT NULL DEFAULT '',
    produto                   varchar(80)  NOT NULL DEFAULT '',
    sequencia                 varchar(10)  NOT NULL DEFAULT '',
    operacao                  varchar(10)  NOT NULL,
    suboperacao               varchar(10)  NOT NULL DEFAULT '',
    descricao_operacao        varchar(255) NOT NULL DEFAULT '',
    centro_trabalho           varchar(20)  NOT NULL DEFAULT '',
    tipo_processo             varchar(40)  NOT NULL DEFAULT '',
    tela_destino              varchar(80)  NOT NULL DEFAULT '',
    status                    varchar(30)  NOT NULL DEFAULT 'EM_ANDAMENTO',

    usuario_inicio            varchar(80)  NOT NULL,
    estacao_inicio            varchar(80)  NOT NULL DEFAULT '',
    iniciado_em               timestamptz  NOT NULL DEFAULT now(),
    -- Codigo EXATAMENTE como lido; jamais substituido por codigo regenerado.
    codigo_barras_inicio      varchar(60)  NOT NULL,

    usuario_termino           varchar(80),
    estacao_termino           varchar(80),
    terminado_em              timestamptz,
    codigo_barras_termino     varchar(60),

    correlation_id            varchar(40)  NOT NULL DEFAULT '',
    idempotency_key           varchar(120) NOT NULL,
    idempotency_key_termino   varchar(120),

    -- Vinculo com o resultado da tela operacional: permite reconstruir o estado apos reinicio e saber
    -- QUAL registro o processo criou (Consumo: codigo_lancamento). Opcional para aberturas manuais.
    resultado_operacional          varchar(40),
    codigo_registro_processo       bigint,
    concluido_operacional_em       timestamptz,
    mensagem_resultado_operacional text,

    criado_em                 timestamptz  NOT NULL DEFAULT now(),
    atualizado_em             timestamptz  NOT NULL DEFAULT now()
);

DO $$
BEGIN
    -- Estados PERSISTIDOS pelas transicoes REAIS do codigo. PENDENTE/BLOQUEADA/LIBERADA/ERRO sao
    -- estados CALCULADOS de tela (operacao sem apontamento) e NAO sao gravados aqui.
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_apontamento_status'
                     AND conrelid = 'desenvolvimento.operacao_producao_apontamento'::regclass) THEN
        ALTER TABLE desenvolvimento.operacao_producao_apontamento
            ADD CONSTRAINT ck_apontamento_status
            CHECK (status IN ('EM_ANDAMENTO','AGUARDANDO_FINALIZACAO','CONCLUIDA','CANCELADA'));
    END IF;

    -- AGUARDANDO_FINALIZACAO e CONCLUIDA exigem resultado operacional VALIDO. Como CONCLUIDA so pode vir
    -- de AGUARDANDO_FINALIZACAO (transicao estrita no repository), o vinculo do processo fica garantido
    -- nos dois estados. Os valores gravados sao os nomes do enum ResultadoExecucaoProcessoApontamento
    -- (ToString()): somente 'ConcluidoLocalmente' e 'ConfirmadoSap' liberam a conclusao da atividade.
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_apontamento_resultado_operacional'
                     AND conrelid = 'desenvolvimento.operacao_producao_apontamento'::regclass) THEN
        ALTER TABLE desenvolvimento.operacao_producao_apontamento
            ADD CONSTRAINT ck_apontamento_resultado_operacional
            CHECK (
                status NOT IN ('AGUARDANDO_FINALIZACAO', 'CONCLUIDA')
                OR (
                    resultado_operacional IS NOT NULL
                    AND resultado_operacional IN ('ConcluidoLocalmente', 'ConfirmadoSap')
                    AND concluido_operacional_em IS NOT NULL
                )
            );
    END IF;

    -- CONCLUIDA exige rastreabilidade completa do termino (impede "termino sem dados").
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_apontamento_termino_completo'
                     AND conrelid = 'desenvolvimento.operacao_producao_apontamento'::regclass) THEN
        ALTER TABLE desenvolvimento.operacao_producao_apontamento
            ADD CONSTRAINT ck_apontamento_termino_completo
            CHECK (status <> 'CONCLUIDA'
                   OR (terminado_em IS NOT NULL
                       AND usuario_termino IS NOT NULL
                       AND codigo_barras_termino IS NOT NULL
                       AND idempotency_key_termino IS NOT NULL));
    END IF;

    -- Termino nunca pode ser anterior ao inicio.
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_apontamento_ordem_cronologica'
                     AND conrelid = 'desenvolvimento.operacao_producao_apontamento'::regclass) THEN
        ALTER TABLE desenvolvimento.operacao_producao_apontamento
            ADD CONSTRAINT ck_apontamento_ordem_cronologica
            CHECK (terminado_em IS NULL OR terminado_em >= iniciado_em);
    END IF;
END $$;

-- ---- Restricoes de concorrencia/idempotencia ----

-- (a) DOIS APONTAMENTOS ATIVOS da mesma operacao: proibido (um usuario/estacao por operacao).
CREATE UNIQUE INDEX IF NOT EXISTS uq_apontamento_ativo_por_operacao
    ON desenvolvimento.operacao_producao_apontamento (numero_ordem, sequencia, operacao, suboperacao)
    WHERE status IN ('EM_ANDAMENTO','AGUARDANDO_FINALIZACAO');

-- (b) CODIGO DE INICIO usado duas vezes: proibido.
CREATE UNIQUE INDEX IF NOT EXISTS uq_apontamento_idempotency_inicio
    ON desenvolvimento.operacao_producao_apontamento (idempotency_key);

-- (c) CODIGO DE TERMINO usado duas vezes: proibido.
CREATE UNIQUE INDEX IF NOT EXISTS uq_apontamento_idempotency_termino
    ON desenvolvimento.operacao_producao_apontamento (idempotency_key_termino)
    WHERE idempotency_key_termino IS NOT NULL;

-- (d) "Termino sem apontamento ativo" e impedido pelo proprio fluxo: o UPDATE de termino exige
--     status = 'AGUARDANDO_FINALIZACAO' (transicao ESTRITA - CONCLUIDA nunca vem de EM_ANDAMENTO direto).
--     Combinado a ck_apontamento_termino_completo e ck_apontamento_resultado_operacional, CONCLUIDA so
--     existe com dados de termino E resultado operacional valido. Nao ha INSERT direto em CONCLUIDA.

CREATE INDEX IF NOT EXISTS ix_apontamento_ordem ON desenvolvimento.operacao_producao_apontamento (numero_ordem);
CREATE INDEX IF NOT EXISTS ix_apontamento_status ON desenvolvimento.operacao_producao_apontamento (status);

-- ============================================================
-- 3. EVENTOS: auditoria de cada leitura
-- ============================================================
CREATE TABLE IF NOT EXISTS desenvolvimento.operacao_producao_evento
(
    codigo_evento_apontamento bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_apontamento        bigint       REFERENCES desenvolvimento.operacao_producao_apontamento(codigo_apontamento) ON DELETE RESTRICT,
    -- Codigo ORIGINAL da leitura: nunca substituido pelo regenerado.
    codigo_original           varchar(60)  NOT NULL,
    formato_codigo            varchar(40)  NOT NULL,
    ordem_producao            varchar(40)  NOT NULL DEFAULT '',
    operacao                  varchar(10)  NOT NULL DEFAULT '',
    codigo_evento             varchar(10)  NOT NULL DEFAULT '',
    usuario                   varchar(80)  NOT NULL DEFAULT '',
    estacao                   varchar(80)  NOT NULL DEFAULT '',
    ocorrido_em               timestamptz  NOT NULL DEFAULT now(),
    status_anterior           varchar(30)  NOT NULL DEFAULT '',
    status_novo               varchar(30)  NOT NULL DEFAULT '',
    resultado                 varchar(40)  NOT NULL DEFAULT '',
    mensagem                  text         NOT NULL DEFAULT '',
    correlation_id            varchar(40)  NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS ix_evento_apontamento ON desenvolvimento.operacao_producao_evento (codigo_apontamento);
CREATE INDEX IF NOT EXISTS ix_evento_ordem ON desenvolvimento.operacao_producao_evento (ordem_producao);
CREATE INDEX IF NOT EXISTS ix_evento_correlation ON desenvolvimento.operacao_producao_evento (correlation_id);

-- ============================================================
-- 4. Permissoes minimas para o app (fugapet_dev_app)
-- ============================================================
DO $$
DECLARE
    v_seq_config text := pg_get_serial_sequence('desenvolvimento.operacao_producao_configuracao', 'codigo_configuracao');
    v_seq_apont  text := pg_get_serial_sequence('desenvolvimento.operacao_producao_apontamento', 'codigo_apontamento');
    v_seq_evento text := pg_get_serial_sequence('desenvolvimento.operacao_producao_evento', 'codigo_evento_apontamento');
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fugapet_dev_app') THEN
        RAISE EXCEPTION 'PROPOSTA: papel fugapet_dev_app inexistente. A aplicacao DEV nao teria acesso aos objetos do 039.';
    END IF;

    -- SEM DELETE: historico de apontamento/evento e preservado; cancelamento e logico (status).
    GRANT SELECT                     ON desenvolvimento.operacao_producao_configuracao TO fugapet_dev_app;
    GRANT SELECT, INSERT, UPDATE     ON desenvolvimento.operacao_producao_apontamento  TO fugapet_dev_app;
    GRANT SELECT, INSERT             ON desenvolvimento.operacao_producao_evento       TO fugapet_dev_app;

    IF v_seq_config IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO fugapet_dev_app', v_seq_config);
    END IF;
    IF v_seq_apont IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO fugapet_dev_app', v_seq_apont);
    END IF;
    IF v_seq_evento IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO fugapet_dev_app', v_seq_evento);
    END IF;
END $$;

-- ============================================================
-- 5. PERMISSOES da rotina CONTROLE_APONTAMENTOS
--    Colunas REAIS da tabela: modulo_permissao / rotina_permissao / acao_permissao /
--    descricao_permissao / situacao_permissao. Idempotente.
--    Enquanto NAO aplicado, a tela faz fallback documentado para LEITURA_PRODUCAO (somente consulta).
-- ============================================================
INSERT INTO desenvolvimento.permissao
    (modulo_permissao, rotina_permissao, acao_permissao, descricao_permissao, situacao_permissao)
-- MVP: SOMENTE as 3 acoes com efeito funcional REAL nesta versao. CONSULTAR_HISTORICO, CANCELAR,
-- REABRIR e IGNORAR_SEQUENCIA NAO sao criadas aqui: nao existe fluxo que as consuma, e permissao ativa
-- sem efeito funcional e falso controle. Ficam para incremental futuro, junto com suas telas/fluxos.
SELECT 'PROCESSO_PRODUCAO', 'CONTROLE_APONTAMENTOS', a.acao, a.descricao, true
  FROM (VALUES
            ('VISUALIZAR', 'Abrir a tela de Controle de Apontamentos e consultar operacoes da OP.'),
            ('INICIAR',    'Registrar o inicio da operacao (leitura do codigo de evento 01).'),
            ('FINALIZAR',  'Registrar o termino da operacao (leitura do codigo de evento 02).')
       ) AS a(acao, descricao)
 WHERE NOT EXISTS (
    SELECT 1 FROM desenvolvimento.permissao p
     WHERE p.modulo_permissao = 'PROCESSO_PRODUCAO'
       AND p.rotina_permissao = 'CONTROLE_APONTAMENTOS'
       AND p.acao_permissao = a.acao);

-- Vinculo idempotente das novas permissoes ao perfil Administrador.
-- NAO atribuir automaticamente aos demais perfis: exige decisao funcional documentada.
INSERT INTO desenvolvimento.perfil_permissao
    (codigo_perfil_acesso, codigo_permissao, situacao_perfil_permissao)
SELECT pa.codigo_perfil_acesso, p.codigo_permissao, true
  FROM desenvolvimento.perfil_acesso pa
 CROSS JOIN desenvolvimento.permissao p
 WHERE pa.nome_perfil_acesso = 'Administrador'
   AND p.modulo_permissao = 'PROCESSO_PRODUCAO'
   AND p.rotina_permissao = 'CONTROLE_APONTAMENTOS'
   AND NOT EXISTS (
        SELECT 1 FROM desenvolvimento.perfil_permissao pp
         WHERE pp.codigo_perfil_acesso = pa.codigo_perfil_acesso
           AND pp.codigo_permissao = p.codigo_permissao);

COMMIT;
